{"name": "删除食物", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\data\\\\record_data.yml'", "trace": "self = <class 'cases.record.test_eating.TestAtEating'>\n\n    def setup_class(self):\n>       food_id = EatingApi().add_food(\"add_food\").json()[\"id\"]\n\ncases\\record\\test_eating.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.recordapi.eating.EatingApi object at 0x000001BD1DC03B00>\n\n    def __init__(self):\n        self.params[\"token\"] = self.base_token\n    \n        _path = os.path.abspath(\"../../data/record_data.yml\")\n>       with open(_path, encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\data\\\\record_data.yml'\n\napi\\recordapi\\eating.py:17: FileNotFoundError"}, "start": 1662691401231, "stop": 1662691401231, "uuid": "76910760-1a3c-4aa5-8377-4bde3745e66e", "historyId": "7a6eed5a148205087a536f27d396fc97", "testCaseId": "756d06ee6f3b8da9321bef012c6acd68", "fullName": "cases.record.test_eating.TestAtEating#test_delete_food", "labels": [{"name": "feature", "value": "record接口"}, {"name": "parentSuite", "value": "cases.record"}, {"name": "suite", "value": "test_eating"}, {"name": "subSuite", "value": "TestAtEating"}, {"name": "host", "value": "DESKTOP-JABQKC0"}, {"name": "thread", "value": "14812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.record.test_eating"}]}